services:
  app:
    image: vadolasi/biblia:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.biblia.rule=Host(`biblia.vitordaniel.com`)"
      - "traefik.http.services.biblia.loadbalancer.server.port=80"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.biblia.rule=Host(`biblia.vitordaniel.com`)"
        - "traefik.http.services.biblia.loadbalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    external: true
